config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/new_posts' => 'homes#new_posts'
  get '/popular' => 'homes#popular'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    put :hide, on: :member
  end

  resources :albums, only: [:new, :show, :create, :edit, :update, :destroy]

  resources :post_images, only: [:new, :show, :create, :index, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :inquiries, only: [:new, :create]

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :albums, dependent: :destroy
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post_image

  # フォローする側からみた関係
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # フォローされる側からみた関係
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  # 対象のユーザーがフォロー済み(passive_relationships)に含まれているか
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  # ゲストログインの際のユーザーデータ作成
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # 退会済みのユーザーでないか否かの確認
  def active_for_authentication?
    super && (self.delete_flag == false)
  end

  validates :name, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @post_images = @user.post_images
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to admins_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:delete_flag)
  end

  # 対象レコードの特定し変数に代入（before_actionで指定のメソッドの実行の際に使用）
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash.now[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash.now[:error] = "必須項目を入力してください。"
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :check_guest, only: :hide

  def show
    @post_images = @user.post_images
    @favorites_list = @user.favorited_posts
    @albums = @user.albums
  end

  def edit
    redirect_to root_path if @user != current_user
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def follows
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  def hide
    @user.update(delete_flag: true)
    reset_session
    flash.now[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def check_guest
    if @user.email == 'guest@example.com'
      redirect_to root_path, notice: "※ゲストユーザーは削除できません。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="edit-prof">
    <h2>Edit Your Profile</h2>
  </div>
  <%= form_with model: @user, local:true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
    <div class="col-md-6">
      <div class="field">
		    <p><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size:"300x300", class:"rounded-circle"; %></p>
		    <p><%= f.attachment_field :profile_image, id: :image %></p>
		　</div>
    </div>

    <div class="col-md-6">
      <table class="form-field">
        <tr>
          <th><%= f.label :name %></th>
          <th class="value"><%= f.text_field :name, autofocus: true %></th>
        </tr>
        <tr>
          <th><%= f.label :introduction %></th>
          <th class="value"><%= f.text_field :introduction, autofocus: true %></th>
        </tr>
        <tr>
          <th><%= f.label :email %><br /></th>
          <th class="value"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></th>
        </tr>
      </table>
      <div class="submit-btn">
        <p><%= f.submit "Update" %></p>
      </div>
    </div>
  </div>
  <div class="withdraw">
    <h2>Or Delete Your Account</h2>
    <%= link_to hide_user_path(@user), method: :put, "data-confirm" => "本当に退会しますか？", class:"text-dark" do %>
      <i class="fas fa-user-slash"></i>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="profile">
  <h1 class="text-center">followers</h1>
  <% @users.each do |user| %>
  <div class="user-list">
    <div class="prof-image">
      <p>
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "150x150", class:"rounded-circle"; %>
        <% end %>
      </p>
    </div>
    <div class="prof-info">
      <p><%= user.name %></p>
      <p id="follow-btn_<%= user.id %>">
        <% if user_signed_in? %>
          <%= render 'relationships/follow-btn', user: user %>
        <% end %>
      </p>
    </div>
  </div>
  <% end %>
</div>

app/views/users/follows.html.erb
<div class="profile">
  <h1 class="text-center">follows</h1>
  <% @users.each do |user| %>
  <div class="user-list">
    <div class="prof-image">
      <p>
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "150x150", class:"rounded-circle"; %>
        <% end %>
      </p>
    </div>
    <div class="prof-info">
      <p><%= user.name %></p>
      <p id="follow-btn_<%= user.id %>">
        <% if user_signed_in? %>
          <%= render 'relationships/follow-btn', user: user %>
        <% end %>
      </p>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="profile">
    <div class="profile-image">
      <p><%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class:"rounded-circle"; %></p>
    </div>
    <div class="user-name">
      <h5><%= @user.name %></h5>
      <% if @user == current_user %>
        <h5>
          <%= link_to edit_user_path, class:"text-dark" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </h5>
      <% else %>
        <h5 id="follow-btn_<%= @user.id %>">
          <% if user_signed_in? %>
            <%= render 'relationships/follow-btn', user: @user %>
          <% end %>
        </h5>
      <% end %>
    </div>
    <div class="introduction">
      <h5>Introduction</h5>
      <p><%= @user.introduction %></p>
    </div>
    <div class="relationships">
      <% if @user == current_user %>
        <h5><%= link_to "follower", followers_user_path(@user.id), class:"text-dark" %></h5>
        <h5><%= link_to "following", follows_user_path(@user.id), class:"text-dark" %></h5>
      <% end %>
    </div>
  </div>

 <div class="wrap">
    <ul id="tab-menu">
      <li><a href="#tab1" class="active">Posts</a></li>
      <% if user_signed_in? %>
      <li><a href="#tab2" class="">Favorites</a></li>
      <% end %>
      <li><a href="#tab3" class="">Albums</a></li>
    </ul>

    <div id="tab-contents">
      <div id="tab1" class="tab">
        <div class="row">
          <%= render "post_images/index", post_images: @post_images %>
        </div>
      </div>

      <div id="tab2" class="tab">
        <div class="row">
          <%= render "post_images/index", post_images: @favorites_list %>
        </div>
      </div>

      <div id="tab3" class="tab">
        <div class="row">
          <% @albums.each do |album| %>
          <div class="album">
            <%= link_to album_path(album) do %>
            <div class="album-body">
              <% if album.post_images.present? %>
                <% album.post_images.first(4).each do |image| %>
                  <%= attachment_image_tag image, :post_image, class: "default_image", size:"150x150" %>
                <% end %>
              <% else %>
                画像はありません。
              <% end %>
            </div>
            <% end %>
            <div class="album-text">
              <span class="album-title"><%= album.title %></span>
              <% if @user == current_user %>
                <span class="album-delete"><%= link_to "削除", album_path(album), method: :delete, data: {confirm: "本当に削除しますか？"} %></span>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>