config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/new_posts' => 'homes#new_posts'
  get '/popular' => 'homes#popular'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    put :hide, on: :member
  end

  resources :albums, only: [:new, :show, :create, :edit, :update, :destroy]

  resources :post_images, only: [:new, :show, :create, :index, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :inquiries, only: [:new, :create]

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update]
  end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :album, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tags(save_post_image_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - save_post_image_tags
    new_tags = save_post_image_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(tag_name: old_name.downcase)
    end

    new_tags.each do |new_name|
      post_image_tag = Tag.find_or_create_by(tag_name: new_name.downcase)
      tags << post_image_tag
    end
  end

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :post_image, presence: true
  # validates :caption, presence: true

  attachment :post_image
end

app/controllers/admins/post_images_controller.rb
class Admins::PostImagesController < ApplicationController
  before_action :set_post_image, only: [:show, :edit, :update]

  def index
    @post_images = PostImage.all.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def update
    @post_image.update(post_image_params)
    redirect_to admins_post_image_path(@post_image)
  end

  private

  def post_image_params
    params.require(:post_image).permit(:is_active)
  end

  # 対象レコードの特定し変数に代入（before_actionで指定のメソッドの実行の際に使用）
  def set_post_image
    @post_image = PostImage.find(params[:id])
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]

  def new
    @post_image = PostImage.new
    @tag = Tag.new
  end

  def create
    @post_image = current_user.post_images.new(post_image_params)
    # splitの指定により、全角半角どちらでも空白での分割が可能
    tag_list = params[:post_image][:tag_names].split(/[[:blank:]]/)
    if @post_image.save
      @post_image.save_tags(tag_list)
      flash[:notice] = "投稿を作成しました"
      redirect_to post_image_path(@post_image)
    else
      render "new"
    end
  end

  def show
    @post_comment = PostComment.new
  end

  def index
    @tags = Tag.all
    # タグ検索の場合
    if params[:tag_id]
      @tag = Tag.find(params[:tag_id])
      @post_images = @tag.post_images
    # ワード検索の場合
    elsif @q = PostImage.ransack(params[:q])
      @post_images = @q.result
    else
      @post_images = PostImage.where(is_active: true)
    end
  end

  def edit
    # @post_imageに結びついたタグを取得し、空白区切りで表示
    @tag_list = @post_image.tags.pluck(:tag_name).join(" ")
    redirect_to root_path if @post_image.user != current_user
  end

  def update
    tag_list = params[:post_image][:tag_names].split(/[[:blank:]]/)
    if @post_image.update(post_image_params)
      @post_image.save_tags(tag_list)
      flash[:notice] = "投稿を更新しました"
      redirect_to post_image_path(@post_image)
    else
      render "edit"
    end
  end

  def destroy
    @post_image.destroy
    flash.now[:notice] = "投稿を削除しました"
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:post_image, :caption, :address)
  end

  def tag_params
    params.require(:post_image).permit(:tag_names)
  end

  def set_post_image
    @post_image = PostImage.find(params[:id])
  end
end

app/helpers/admins/post_images_helper.rb
module Admins::PostImagesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/admins/post_images/edit.html.erb
<div class="container">
  <div class="post-info">
    <h3>Edit This Post's Status</h3>
  </div>
  <%= form_with model: @post_image, url: admins_post_image_path(@post_image), local:true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= attachment_image_tag @post_image, :post_image, size:"400x400" %>
      </div>
    </div>

    <div class="col-md-6">
      <table class="form-field">
        <tr>
          <th>Caption：<%= @post_image.caption %></th>
        </tr>
        <tr>
          <th>
            <p>Tags：
              <% @post_image.tags.each do |tag| %>
                <span>
                  # <%= tag.tag_name %>
                </span>
              <% end %>
            </p>
          </th>
        <tr>
          <th>Place：<%= @post_image.address %></th>
        </tr>
        <tr>
          <th>
            <div>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, "有効" %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "無効" %>
            </div>
          </th>
        </tr>
      </table>
      <%= f.submit "Update", class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/admins/post_images/index.html.erb
<div class="container">
  <div class="logo">
    <%= image_tag "Label.png" %>
  </div>
  <div class="row">
    <%= render "post_images/index", post_images: @post_images %>
  </div>
</div>

app/views/admins/post_images/show.html.erb
<div class="container">
  <div class="post-image">
    <p class="card-item mx-auto mt-4 shadow-lg"><%= attachment_image_tag @post_image, :post_image, size:"600x600" %></p>
  </div>
  <div class="user-profile">
    <div class="profile-image">
      <p>
        <%= link_to admins_user_path(@post_image.user) do %>
          <%= attachment_image_tag @post_image.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class:"rounded-circle"; %>
        <% end %>
      </p>
      <p><%= @post_image.user.name %></p>
    </div>
    <h5>
      <%= link_to edit_admins_post_image_path, class:"text-dark" do %>
        Edit This Post's Status <i class="fas fa-edit"></i>
      <% end %>
    </h5>
  </div>

  <div class="caption">
    <p><%= @post_image.caption %></p>
  </div>

  <div class="status">
    <% if @post_image.is_active == true %>
      <p>ステータス：有効</p>
    <% else %>
      <p>ステータス：無効</p>
    <% end %>
  </div>

  <div class="tags text-center">
    <%= render "layouts/tags", tags: @post_image.tags %>
  </div>

  <div class="row">
    <div class="col-md-7"></div>
    <div class="col-md-5">
      <div class="comment">
        <p>コメント<i class="far fa-comment-alt"></i>：<%= @post_image.post_comments.count %></p>
        <% @post_image.post_comments.each do |post_comment| %>
          <p>
            <%= link_to user_path(post_comment.user) do %>
              <%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg", size: "50x50", class:"rounded-circle"; %>
            <% end %>
            <span><%= post_comment.user.name %></span>
            <span><%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %></span>
          </p>
          <%= link_to "Delete This Comment", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</di>

  <% if @post_image.address.present? %>
    <div class="row">
      <div id="map"></div>
    </div>
  <% end %>

  <script type="text/javascript">
  function initMap() {
    var test ={lat: <%= @post_image.latitude %>, lng: <%= @post_image.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @post_image.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
  </script>

  <script async defer
                src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap">
  </script>

  <style type="text/css">
    #map { height: 500px;
           width: 100%;}
  </style>