config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/new_posts' => 'homes#new_posts'
  get '/popular' => 'homes#popular'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    put :hide, on: :member
  end

  resources :albums, only: [:new, :show, :create, :edit, :update, :destroy]

  resources :post_images, only: [:new, :show, :create, :index, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :inquiries, only: [:new, :create]

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :post_image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :album, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tags(save_post_image_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - save_post_image_tags
    new_tags = save_post_image_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(tag_name: old_name.downcase)
    end

    new_tags.each do |new_name|
      post_image_tag = Tag.find_or_create_by(tag_name: new_name.downcase)
      tags << post_image_tag
    end
  end

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :post_image, presence: true
  # validates :caption, presence: true

  attachment :post_image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  before_save :downcase_tag_name

  has_many :tag_maps, dependent: :destroy
  has_many :post_images, through: :tag_maps

  validates :tag_name, presence: true, uniqueness: true, length: { maximum: 50 }

  private

  def downcase_tag_name
    tag_name.downcase!
  end
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post_image
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :albums, dependent: :destroy
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post_image

  # フォローする側からみた関係
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # フォローされる側からみた関係
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  # 対象のユーザーがフォロー済み(passive_relationships)に含まれているか
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  # ゲストログインの際のユーザーデータ作成
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # 退会済みのユーザーでないか否かの確認
  def active_for_authentication?
    super && (self.delete_flag == false)
  end

  validates :name, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_tags, except: :about

  def top
    @post_images = PostImage.where(is_active: true)
  end

  def about
  end

  def new_posts
    @post_images = PostImage.all.order(created_at: :desc)
  end

  # いいね数順に一覧表示
  def popular
    @post_images = PostImage.includes(:favorited_users).sort { |a, b| b.favorited_users.count <=> a.favorited_users.count}
  end

  private

  def set_tags
    @tags = Tag.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :check_guest, only: :hide

  def show
    @post_images = @user.post_images
    @favorites_list = @user.favorited_posts
    @albums = @user.albums
  end

  def edit
    redirect_to root_path if @user != current_user
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def follows
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  def hide
    @user.update(delete_flag: true)
    reset_session
    flash.now[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def check_guest
    if @user.email == 'guest@example.com'
      redirect_to root_path, notice: "※ゲストユーザーは削除できません。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer bg-light">
  <p>Copyright © 2021 ToLabel INC. All Rights Reserved.</p>
</div>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar bg-light">
    <div class="container">
      <i class="fas fa-bars header-icon"></i>
      <% if admin_signed_in? %>
        <div class="nav-list mx-auto">
          <%= link_to admins_post_images_path do %>
            <%= image_tag 'Label.png' %>
          <% end %>
        </div>
      <% else %>
        <ul class="navbar ml-auto">
          <li class="nav-list">
            <%= link_to new_posts_path do %>
              <%= image_tag 'new.png' %>
            <% end %>
          </li>
          <li class="nav-list">
            <%= link_to root_path do %>
              <%= image_tag 'Label.png' %>
            <% end %>
          </li>
          <li class="nav-list">
            <%= link_to popular_path do %>
              <%= image_tag 'popular.png' %>
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search-form">
  <%= search_form_for q, url: post_images_path do |f| %>
    <%= f.text_field :caption_or_address_cont ,placeholder: 'write word in here', class:"search-box" %>
    <%= f.submit "search", class: 'search-btn' %>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<aside class="sidebar">
  <div class="sidebar-inner">
    <h4 class="sidebar-ttl">Menu</h4>
    <i class="fas fa-times-circle sidebar-icon"></i>
  </div>
  <ul class="sidebar-list">
  <% if user_signed_in? %>
    <li class="sidebar-txt"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    <li class="sidebar-txt"><%= link_to "Create Post", new_post_image_path %></li>
    <li class="sidebar-txt"><%= link_to "Create Album", new_album_path %></li>
    <li class="sidebar-txt"><%= link_to "My Page", user_path(current_user.id) %></li>
    <li class="sidebar-txt"><%= link_to "Contact Us", new_inquiry_path %></li>
  <% elsif admin_signed_in? %>
    <li class="sidebar-txt"><%= link_to "Log Out", destroy_admin_session_path, method: :delete %></li>
    <li class="sidebar-txt"><%= link_to "Users", admins_users_path %></li>
    <li class="sidebar-txt"><%= link_to "Posts", admins_post_images_path %></li>
  <% else %>
    <li class="sidebar-txt"><%= link_to "Sign Up", new_user_registration_path %></li>
    <li class="sidebar-txt"><%= link_to "Log In", new_user_session_path %></li>
    <li class="sidebar-txt"><%= link_to "About", about_path %></li>
  <% end %>
  </ul>
</aside>
<div class="sidebar-bg"></div>

app/views/layouts/_tags.html.erb
  <div class="tags">
    <% tags.each do |tag| %>
      <% if tag.post_images.present? %>
        <span>
          <%= link_to post_images_path(tag_id: tag.id), class:"text-dark m-10" do %>
            <i class="fas fa-tag"></i> <%= tag.tag_name %>
          <% end %>
        </span>
      <% end %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToLabel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="text-center"><%= flash.now[:notice] %></div>
    <div class="text-center"><%= flash.now[:error] %></div>
    <div class="text-center"><%= flash.now[:email] %></div>
    <%= yield %>
    <%= render 'layouts/sidebar' %>
    <%= render 'layouts/footer' %>
  </body>
</html>