config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/new_posts' => 'homes#new_posts'
  get '/popular' => 'homes#popular'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    put :hide, on: :member
  end

  resources :albums, only: [:new, :show, :create, :edit, :update, :destroy]

  resources :post_images, only: [:new, :show, :create, :index, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :inquiries, only: [:new, :create]

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update]
  end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :album, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tags(save_post_image_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - save_post_image_tags
    new_tags = save_post_image_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(tag_name: old_name.downcase)
    end

    new_tags.each do |new_name|
      post_image_tag = Tag.find_or_create_by(tag_name: new_name.downcase)
      tags << post_image_tag
    end
  end

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :post_image, presence: true
  # validates :caption, presence: true

  attachment :post_image
end

app/controllers/admins/post_images_controller.rb
class Admins::PostImagesController < ApplicationController
  before_action :set_post_image, only: [:show, :edit, :update]

  def index
    @post_images = PostImage.all.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def update
    @post_image.update(post_image_params)
    redirect_to admins_post_image_path(@post_image)
  end

  private

  def post_image_params
    params.require(:post_image).permit(:is_active)
  end

  # 対象レコードの特定し変数に代入（before_actionで指定のメソッドの実行の際に使用）
  def set_post_image
    @post_image = PostImage.find(params[:id])
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]

  def new
    @post_image = PostImage.new
    @tag = Tag.new
  end

  def create
    @post_image = current_user.post_images.new(post_image_params)
    # splitの指定により、全角半角どちらでも空白での分割が可能
    tag_list = params[:post_image][:tag_names].split(/[[:blank:]]/)
    if @post_image.save
      @post_image.save_tags(tag_list)
      flash[:notice] = "投稿を作成しました"
      redirect_to post_image_path(@post_image)
    else
      render "new"
    end
  end

  def show
    @post_comment = PostComment.new
  end

  def index
    @tags = Tag.all
    # タグ検索の場合
    if params[:tag_id]
      @tag = Tag.find(params[:tag_id])
      @post_images = @tag.post_images
    # ワード検索の場合
    elsif @q = PostImage.ransack(params[:q])
      @post_images = @q.result
    else
      @post_images = PostImage.where(is_active: true)
    end
  end

  def edit
    # @post_imageに結びついたタグを取得し、空白区切りで表示
    @tag_list = @post_image.tags.pluck(:tag_name).join(" ")
    redirect_to root_path if @post_image.user != current_user
  end

  def update
    tag_list = params[:post_image][:tag_names].split(/[[:blank:]]/)
    if @post_image.update(post_image_params)
      @post_image.save_tags(tag_list)
      flash[:notice] = "投稿を更新しました"
      redirect_to post_image_path(@post_image)
    else
      render "edit"
    end
  end

  def destroy
    @post_image.destroy
    flash.now[:notice] = "投稿を削除しました"
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:post_image, :caption, :address)
  end

  def tag_params
    params.require(:post_image).permit(:tag_names)
  end

  def set_post_image
    @post_image = PostImage.find(params[:id])
  end
end

app/helpers/admins/post_images_helper.rb
module Admins::PostImagesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_form.html.erb
<%= form_with model: post_image, local:true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <div class="col-md-6">
    <div class="field">
      <div class="item-image">
        <%= attachment_image_tag post_image, :post_image, fallback: "no_image.jpg", size:"400x400" %>
      </div>
      <%= f.attachment_field :post_image %>
    </div>
  </div>

  <div class="col-md-6">
    <table class="form-field">
      <tr>
        <th><%= f.label :Caption %></th>
        <th><%= f.text_field :caption, autofocus: true %></th>
      </tr>
      <tr>
        <th><%= f.label :Label %></th>
        <th><%= f.text_field :tag_names, value: tag_list %></th>
      </tr>
      <tr>
        <th><%= f.label :Place %></th>
        <th><%= f.text_area :address, autofocus: true %></th>
      </tr>
    </table>
    <div class="submit-btn">
      <p><%= f.submit "Upload" %></p>
    </div>
  </div>
</div>
<% end %>

app/views/post_images/_index.html.erb
<% post_images.each do |post| %>
  <div class="image-item mt-4 shadow-lg">
    <% if admin_signed_in? %>
      <%= link_to admins_post_image_path(post) do %>
        <%= attachment_image_tag post, :post_image, size:"200x200" %>
      <% end %>
    <% else %>
      <%= link_to post_image_path(post) do %>
        <%= attachment_image_tag post, :post_image, size:"200x200" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/post_images/edit.html.erb
<div class="container">
  <div class="post-info">
    <h3>Edit This Post</h3>
  </div>
  <%= render "post_images/form", post_image: @post_image, tag_list: @tag_list %>
  <div class="delete-post">
    <h3>Or Delete This Post</h3>
    <%= link_to post_image_path(@post_image), method: :delete, "data-confirm" => "本当に削除しますか？", class:"text-dark" do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </div>
</div>

app/views/post_images/index.html.erb
<div class="container">
  <div class="logo">
    <%= image_tag "Label.png" %>
  </div>
  <div class="row">
    <%= render "layouts/search", q: @q %>
  </div>
  <div class="row">
    <%= render "layouts/tags", tags: @tags %>
  </div>
  <div class="row">
    <%= render "post_images/index", post_images: @post_images %>
  </div>
</div>

app/views/post_images/new.html.erb
<div class="container">
  <div class="post-info">
    <h3>Create Post</h3>
  </div>
  <%= render "post_images/form", post_image: @post_image, tag_list: @tag_list %>
</div>

app/views/post_images/show.html.erb
<div class="container">
  <div class="post-image">
    <p class="card-item mx-auto mt-4 shadow-lg">
      <%= attachment_image_tag @post_image, :post_image, size:"600x600" %>
    </p>
  </div>
  <div class="icon">
    <ul class="icon-list">
      <li class="icon-item" id="favorite-btn_<%= @post_image.id %>">
        <%= render 'favorites/favorite-btn', post_image: @post_image %>
      </li>
      <li class="icon-item" id="post-comment_<%= @post_image.id %>">
        <p class="comments-count"><span class="comment-count"><%= @post_image.post_comments.count %></span><i class="far fa-comment-alt"></i></p>
      </li>
    </ul>
  </div>
  <div class="user-profile">
    <% if @post_image.user == current_user %>
      <h5>
        <%= link_to edit_post_image_path, class:"text-dark" do %>
          Edit This Post <i class="fas fa-edit"></i>
        <% end %>
      </h5>
    <% else %>
      <div class="profile-image">
        <p>
          <%= link_to user_path(@post_image.user) do %>
            <%= attachment_image_tag @post_image.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class:"rounded-circle"; %>
          <% end %>
        </p>
      </div>
      <div class="user-name">
        <h5><%= @post_image.user.name %></h5>
        <h5 id="follow-btn_<%= @post_image.user.id %>">
          <% if user_signed_in? %>
            <%= render 'relationships/follow-btn', user: @post_image.user %>
          <% end %>
        </h5>
      </div>
    <% end %>
  </div>

  <div class="caption mt-5">
    <p><%= @post_image.caption %></p>
  </div>

  <% if @post_image.user == current_user %>
  <div class="status">
    <% if @post_image.is_active == true %>
      <p>ステータス：有効</p>
    <% else %>
      <p>ステータス：無効</p>
    <% end %>
  </div>
  <% end %>

  <div class="tags text-center">
    <%= render "layouts/tags", tags: @post_image.tags %>
  </div>

  <div class="row">
    <div class="col-md-7"></div>
    <div class="col-md-5">
        <div class="comment">
          <p>コメント<i class="far fa-comment-alt">
            </i>：<span class="comment-count"><%= @post_image.post_comments.count %></span>
          </p>
          <div id="comment_list">
            <%= render 'post_comments/index', post_image: @post_image %>
          </div>
        </div>

      <% if user_signed_in? %>
        <div class="comment-form">
          <%= form_with(model:[@post_image, @post_comment]) do |f| %>
            <p><%= f.text_area :comment, rows:'5', placeholder: "コメント", style:"width:100%"; %></p>
            <p><%= f.submit "Create" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if @post_image.address.present? %>
  <div class="row">
    <div id="map"></div>
  </div>
<% end %>

  <script type="text/javascript">
  function initMap() {
    var test ={lat: <%= @post_image.latitude %>, lng: <%= @post_image.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @post_image.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
  </script>

  <script async defer
                src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY']%>&callback=initMap">
  </script>

  <style type="text/css">
    #map { height: 500px;
           width: 100%;}
  </style>